apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgASsGvW3yU2Q2hK4ODqZFd2L91JWOod4WtrV7xSROoilOfnlt8JZCakK1GIoeJQNYByOL9BLB8YhMmoTBZ1zqByvsrt/G39GMQYpfqbEakNGQrlZReFbPODQo+L7d6AhNHesOv8eK/a0BqoEkxQ4Gs4/Wq2Is25cp4lhmaEqRGvEAnMkZDw3Y8gCZnieMzs+xwDpofnZ8DMzT8uDMenSaDvNsEFVxe60xsj2as0b9bJxP+uZirzrhgN+NOE02qiiOtxwmqejmVN8TOyic/e+u1Mrbs0Fei+ZHNRp0AbD6pKrQfbZEA9BfwY0GTZPhZBhAwmBi+kYIxPA+qHXYjnFGa5qSxtAyNeelvrnCTYbTSG1msYD6GGIKpUb/PxDwVFKC8I8e1xYPg4j5Sqhyr4W5zKI2wkMav1KWT8DcX71nY7dcwboRmSePKbn+7DdRhAzDE5SPUarblzBd0oNLfWv7Dx4HuwqDdSpv4zhlhz9q0DVP/ik7jKxBfoYK2OsGKJMw4rr8rb21sm8LkQ2+xj/CtwxaaBufZk0wnBJVcGnaIZ9qy2/ctme/wsw365rRS9qKds3SD/zgX93bJJDGmlzg8h440uE6HQJ1956yr47E91JysHpZuEwJchDRGqvy6lYGbR2WIuTseOdtsNhSdzH/5Nj6U/Olw/k+Lc4uN43B/gKcb7ewNp+rTp0j9+dSiF3gxi9XeQggpMIKv+qakuEjrOlzdyt4ylHxLTOhSkpsf6aZUWMUp0dAaU8TbyhXyzubd4mOmgguDUfImt/N4ZOM7OUMVdeDnw0HN6MA4Gt/pNNx2xnrkUcDTLTxfn8KGwPxScHuH710venqAeBTFta2Ir5WgTuFY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

