apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBYSM241g5xBpDt1QFLjpS1fP6kGuJX6lXJJ0EJ4oTtPL9Am5G9lUVdQsXemGSunxkeD/SN2ZToEZK64iZoNdQkgjua0BB63Pk6V7Oryv43TrfHtZYqFKElnvP/FpGrEuzlx8Zodgt2Ezdpyus/kngcCFEJK4RVexh6yoVatDQEOMApvlGNDGO1dB1y0rQMvNLDsZ/wPjU7MwSjmbBraMvt2XYN9jnxuzZ9OoOB0Bbu6vtK8ZzcGpCeNdYxPaOU0zXXchATy3Z0QjH+TNjKB2hH18rREGRvSi5D1vwyR9vmbSgxOVDPBzy3NTSrkzAgLnT4uxG83sUTgtm1OlKnoNmGzMz2jh+PaKINqkT20DSmseKY/f2qqNof8aJnetOiRKvuxuWiWE2hxjpj1tLCPo8zl+vnUWyw3T1JyzzD0tLxECSpRcqmoTCbsXM0iylTd4nL6t0WO3yzN3jdwMbuFLmAKN6otqtc8FswyaphnoyKJSmAExDJwSMUTR/TDbHvArWPtEXyU5nzScKcFEUGVqw6Pa7EWE5a4rKxae7ZdkuHvPnS7HE2dV01wZ6Mln7IUAEbK/cB27e56VBjTDUvvk/KPLnHTa2WkOyN6ICSWL2mLFtpfVpUAB3JIEO001NuXcgSmGNkVAPltS5qlo9HFY8FCgTb48ioMFwYpIA9hoXUIS2hdVUhBKKqDVY7o0whO0S+owTD1c06Kk7O+URZL27H4XlIFuCrZ0bW82lkefE+fwZCq2YFaLKmGqNEd74eZzvZzXma90Xl9fkeomyxw0QT6knFEuCb8bU5v8/bjIelWbIncaWkLJ9W4iAYO24Gv6Q90u4z5aweOT20kF5Tnz5CFv59DrQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

